# Generated by Django 4.0.4 on 2022-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikkeli',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('article_title', models.CharField(max_length=50)),
                ('article_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sivun_tiedot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.FileField(upload_to='')),
                ('Header Background', models.FileField(upload_to='')),
                ('Main title', models.CharField(max_length=50)),
                ('Subtitle', models.CharField(max_length=200)),
                ('Page description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
