# Generated by Django 4.0.4 on 2022-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonewebmain', '0002_artikkeli_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikkeli',
            name='article_tech',
            field=models.CharField(default='', max_length=50),
        ),
    ]
