# Generated by Django 4.0.4 on 2022-07-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonewebmain', '0003_artikkeli_article_tech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikkeli',
            old_name='article_title',
            new_name='Artikkelin_otsikko',
        ),
        migrations.RenameField(
            model_name='artikkeli',
            old_name='article_text',
            new_name='Artikkelin_teksti',
        ),
        migrations.RenameField(
            model_name='artikkeli',
            old_name='article_tech',
            new_name='koodikielet',
        ),
    ]
