# Generated by Django 4.0.6 on 2022-07-18 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonewebmain', '0004_rename_article_title_artikkeli_artikkelin_otsikko_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikkeli',
            name='Artikkelin_teksti',
        ),
        migrations.AddField(
            model_name='artikkeli',
            name='article_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
