# Generated by Django 4.0.6 on 2022-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonewebmain', '0007_artikkeli_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkeli',
            name='article_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
