# Generated by Django 4.0.6 on 2022-07-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonewebmain', '0008_alter_artikkeli_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikkeli',
            name='article_slug',
        ),
        migrations.AddField(
            model_name='artikkeli',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
